# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:           /:categories/:title/
#relative_permalinks: true

# Setup
title:            ASP-Ajaxed
tagline:          ''
description:      ''
url:              http://asp-ajaxed.org
baseurl:          /
imageurl:         ''
only_frontmatter_categories: true
tag_pages_layout: tagpage
show_drafts:      false

author:
  name:           'Mark Bussell Jr. (AnonJr)'
  url:            https://twitter.com/anonjr

paginate:         5
paginate_path:    "page/:num"

# Custom vars
version:          2.1.1

github:
  repo:           https://github.com/ASP-Ajaxed

# Google Analytics
google_analytics_tracking_id:

# Misc
exclude:
  - _misc
  - readme.md
  - .gitignore
  - .git
